// DataPulse-India dashboard.
//
// Every figure rendered here comes from data/summary.json, which the pipeline
// generates from the collected parquet (`datapulse summarize`). Nothing on this
// page is hardcoded sample data -- if a dataset has not been collected yet, it
// says so rather than showing a placeholder number.

const SUMMARY_URL = "data/summary.json";
const $ = (id) => document.getElementById(id);

const state = { datasets: [], active: null, filter: "all", query: "" };

const fmt = (n) => (typeof n === "number" ? n.toLocaleString("en-IN") : n ?? "—");
const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const titleCase = (c) => c.replace(/_/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
const cell = (v) =>
  v === null || v === undefined ? "—" : typeof v === "number" ? v.toLocaleString("en-IN") : v;
const emptyState = (msg) => `<p class="muted empty-state">${esc(msg)}</p>`;

async function init() {
  let summary;
  try {
    const resp = await fetch(SUMMARY_URL, { cache: "no-store" });
    if (!resp.ok) throw new Error(String(resp.status));
    summary = await resp.json();
  } catch {
    $("pipelineStatus").textContent = "Summary unavailable";
    $("panelDescription").textContent =
      "data/summary.json could not be loaded. It is generated by `datapulse summarize` during the nightly run.";
    return;
  }

  state.datasets = summary.datasets || [];
  $("provenance").textContent =
    `Summary generated ${summary.generated_at} · every figure on this page is derived from the collected dataset.`;

  const collecting = state.datasets.filter((d) => d.rows > 0).length;
  $("pipelineStatus").textContent =
    collecting > 0 ? `${collecting} dataset${collecting > 1 ? "s" : ""} collecting` : "No data yet";

  renderTabs();
  select(state.datasets.find((d) => d.rows > 0) || state.datasets[0]);
}

function renderTabs() {
  const nav = $("domainTabs");
  nav.innerHTML = "";
  state.datasets.forEach((d) => {
    const btn = document.createElement("button");
    btn.className = "tab-btn" + (d.rows === 0 ? " is-empty" : "");
    // A dataset with no rows is labelled as such -- never dressed up as live.
    const tag =
      d.rows > 0 ? `${fmt(d.rows)} rows · ${d.days} day${d.days > 1 ? "s" : ""}` : "Not collecting yet";
    btn.innerHTML = '<span class="tab-info"><span class="tab-title"></span><span class="tab-tag"></span></span>';
    btn.querySelector(".tab-title").textContent = d.label;
    btn.querySelector(".tab-tag").textContent = tag;
    btn.onclick = () => select(d);
    nav.append(btn);
  });
}

function select(dataset) {
  if (!dataset) return;
  state.active = dataset;
  state.filter = "all";
  state.query = "";
  const searchBox = $("searchInput");
  if (searchBox) searchBox.value = "";

  const idx = state.datasets.indexOf(dataset);
  [...$("domainTabs").children].forEach((b, i) => b.classList.toggle("active", i === idx));

  $("panelTitle").textContent = dataset.label;
  $("chartTitle").textContent = dataset.chart_title || "";

  if (!dataset.rows) {
    $("panelDescription").textContent =
      "This dataset has no collected data yet. Its pipeline is defined but not enabled.";
    $("chartBadge").textContent = "";
    $("analyticsChart").innerHTML = emptyState("No data collected for this dataset yet.");
    $("tableHead").innerHTML = "";
    $("tableBody").innerHTML = "";
    $("filterPills").innerHTML = "";
    setKpis(null);
    return;
  }

  $("panelDescription").textContent = dataset.preview_note;
  $("chartBadge").textContent = `Top ${dataset.chart.labels.length}`;
  setKpis(dataset);
  drawChart(dataset.chart);
  renderPills(dataset);
  renderTable(dataset);
}

function setKpis(d) {
  const values = ["kpiTotalRows", "kpiMarkets", "kpiTopCommodity", "kpiStatus"];
  const subs = ["kpiTotalRowsSub", "kpiMarketsSub", "kpiTopCommoditySub", "kpiStatusSub"];
  if (!d) {
    values.forEach((id) => ($(id).textContent = "—"));
    subs.forEach((id) => ($(id).textContent = ""));
    return;
  }
  const distinct = (d.stats && d.stats.distinct) || {};
  const top = d.stats && d.stats.top_by_count;

  $("kpiTotalRows").textContent = fmt(d.rows);
  $("kpiTotalRowsSub").textContent = `across ${d.days} collection day${d.days > 1 ? "s" : ""}`;

  $("kpiMarkets").textContent = fmt(distinct.market);
  $("kpiMarketsSub").textContent = distinct.state ? `in ${fmt(distinct.state)} states & UTs` : "";

  $("kpiTopCommodity").textContent = top ? top.value : "—";
  $("kpiTopCommoditySub").textContent = top ? `${fmt(top.reports)} market reports` : "";

  $("kpiStatus").textContent = d.last_collected || "—";
  $("kpiStatusSub").textContent = "schema-validated on write";
}

// Bar chart drawn as inline SVG -- no chart library, so nothing loads from a CDN.
function drawChart(chart) {
  const host = $("analyticsChart");
  const labels = chart.labels || [];
  const values = chart.values || [];
  if (!labels.length) {
    host.innerHTML = emptyState("No chartable values for this dataset.");
    return;
  }

  const W = 900;
  const H = 400;
  const pad = { top: 16, right: 16, bottom: 110, left: 72 };
  const plotW = W - pad.left - pad.right;
  const plotH = H - pad.top - pad.bottom;
  const max = Math.max(...values) || 1;
  const band = plotW / labels.length;
  const barW = Math.min(band * 0.62, 56);
  const ticks = 4;

  const grid = Array.from({ length: ticks + 1 }, (_, i) => {
    const v = (max / ticks) * i;
    const y = pad.top + plotH - (v / max) * plotH;
    return (
      `<line x1="${pad.left}" y1="${y}" x2="${W - pad.right}" y2="${y}" class="grid"/>` +
      `<text x="${pad.left - 10}" y="${y + 4}" class="axis" text-anchor="end">${Math.round(v).toLocaleString("en-IN")}</text>`
    );
  }).join("");

  const bars = labels
    .map((label, i) => {
      const v = values[i];
      const h = (v / max) * plotH;
      const x = pad.left + band * i + (band - barW) / 2;
      const y = pad.top + plotH - h;
      const labelY = pad.top + plotH + 18;
      const short = label.length > 16 ? label.slice(0, 15) + "…" : label;
      return (
        `<g><rect x="${x}" y="${y}" width="${barW}" height="${h}" rx="5" class="bar">` +
        `<title>${esc(label)}: ${v.toLocaleString("en-IN")}</title></rect>` +
        `<text x="${x + barW / 2}" y="${labelY}" class="axis tick" text-anchor="end" ` +
        `transform="rotate(-40 ${x + barW / 2} ${labelY})">${esc(short)}</text></g>`
      );
    })
    .join("");

  host.innerHTML =
    `<svg viewBox="0 0 ${W} ${H}" role="img" preserveAspectRatio="xMidYMid meet" ` +
    `aria-label="${esc($("chartTitle").textContent)}">${grid}` +
    `<line x1="${pad.left}" y1="${pad.top + plotH}" x2="${W - pad.right}" y2="${pad.top + plotH}" class="axis-line"/>` +
    `${bars}</svg>`;
}

function renderPills(dataset) {
  // Pills come from the data's own top values, so they always match what is there.
  const host = $("filterPills");
  host.innerHTML = "";
  ["all"].concat(dataset.chart.labels.slice(0, 5)).forEach((v) => {
    const b = document.createElement("button");
    b.className = "pill" + (v === state.filter ? " active" : "");
    b.textContent = v === "all" ? "All" : v;
    b.onclick = () => {
      state.filter = v;
      renderPills(dataset);
      renderTable(dataset);
    };
    host.append(b);
  });
}

function renderTable(dataset) {
  const rows = dataset.preview || [];
  const columns = rows.length ? Object.keys(rows[0]) : [];
  $("tableHead").innerHTML = `<tr>${columns.map((c) => `<th>${esc(titleCase(c))}</th>`).join("")}</tr>`;

  const q = state.query.toLowerCase();
  const pill = state.filter.toLowerCase();
  const visible = rows.filter((r) => {
    const blob = Object.values(r).join(" ").toLowerCase();
    return (!q || blob.includes(q)) && (state.filter === "all" || blob.includes(pill));
  });

  $("tableBody").innerHTML = visible.length
    ? visible.map((r) => `<tr>${columns.map((c) => `<td>${esc(cell(r[c]))}</td>`).join("")}</tr>`).join("")
    : `<tr><td colspan="${columns.length || 1}" class="muted">No rows match this filter.</td></tr>`;
}

const search = $("searchInput");
if (search) {
  search.addEventListener("input", (e) => {
    state.query = e.target.value;
    if (state.active) renderTable(state.active);
  });
}

init();
