// DataPulse-India dashboard.
//
// Every figure rendered here comes from data/summary.json, which the pipeline
// generates from the collected parquet (`datapulse summarize`). Nothing on this
// page is hardcoded sample data -- if a dataset has not been collected yet, it
// says so rather than showing a placeholder number.

const SUMMARY_URL = "data/summary.json";
const $ = (id) => document.getElementById(id);

const state = { datasets: [], active: null, filter: "all", query: "" };

const fmt = (n) => (typeof n === "number" ? n.toLocaleString("en-IN") : n ?? "—");
const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const titleCase = (c) => c.replace(/_/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
const cell = (v) =>
  v === null || v === undefined ? "—" : typeof v === "number" ? v.toLocaleString("en-IN") : v;
// "2026-08-25T12:50:09+00:00" means nothing at a glance. People read time in
// relation to now, and Indian prices in IST.
function timeAgo(iso) {
  const then = new Date(iso);
  if (isNaN(then)) return "";
  const mins = Math.round((Date.now() - then) / 60000);
  if (mins < 2) return "just now";
  if (mins < 60) return `${mins} minutes ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs} hour${hrs > 1 ? "s" : ""} ago`;
  const days = Math.round(hrs / 24);
  return days === 1 ? "yesterday" : `${days} days ago`;
}

function niceDate(value) {
  const d = new Date(value);
  if (isNaN(d)) return value || "—";
  return d.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
}

const emptyState = (msg) => `<p class="muted empty-state">${esc(msg)}</p>`;

async function init() {
  let summary;
  try {
    const resp = await fetch(SUMMARY_URL, { cache: "no-store" });
    if (!resp.ok) throw new Error(String(resp.status));
    summary = await resp.json();
  } catch {
    $("pipelineStatus").textContent = "Summary unavailable";
    $("panelDescription").textContent =
      "data/summary.json could not be loaded. It is generated by `datapulse summarize` during the nightly run.";
    return;
  }

  state.datasets = summary.datasets || [];
  const when = summary.generated_at;
  $("provenance").textContent =
    `Last updated ${timeAgo(when)} (${niceDate(when)}). Every number here is calculated from the ` +
    `collected data — nothing on this page is typed in by hand.`;

  const collecting = state.datasets.filter((d) => d.rows > 0).length;
  $("pipelineStatus").textContent =
    collecting > 0 ? `Updated ${timeAgo(summary.generated_at)}` : "No data yet";

  renderTabs();
  select(state.datasets.find((d) => d.rows > 0) || state.datasets[0]);
}

function renderTabs() {
  const nav = $("domainTabs");
  nav.innerHTML = "";
  state.datasets.forEach((d) => {
    const btn = document.createElement("button");
    btn.className = "tab-btn" + (d.rows === 0 ? " is-empty" : "");
    // A dataset with no rows is labelled as such -- never dressed up as live.
    const tag =
      d.rows > 0 ? `${fmt(d.rows)} prices` : "Coming soon";
    btn.innerHTML = '<span class="tab-info"><span class="tab-title"></span><span class="tab-tag"></span></span>';
    btn.querySelector(".tab-title").textContent = d.label;
    btn.querySelector(".tab-tag").textContent = tag;
    btn.onclick = () => select(d);
    nav.append(btn);
  });
}

function select(dataset) {
  if (!dataset) return;
  state.active = dataset;
  state.filter = "all";
  state.query = "";
  const searchBox = $("searchInput");
  if (searchBox) searchBox.value = "";

  const idx = state.datasets.indexOf(dataset);
  [...$("domainTabs").children].forEach((b, i) => b.classList.toggle("active", i === idx));

  $("panelTitle").textContent = dataset.label;
  $("chartTitle").textContent = dataset.chart_title || "";

  if (!dataset.rows) {
    $("panelDescription").textContent =
      "We are not collecting this one yet. The pipeline is built and ready to switch on.";
    $("chartBadge").textContent = "";
    $("analyticsChart").innerHTML = emptyState("No data collected for this dataset yet.");
    $("tableHead").innerHTML = "";
    $("tableBody").innerHTML = "";
    $("filterPills").innerHTML = "";
    setKpis(null);
    return;
  }

  $("panelDescription").textContent = dataset.preview_note;
  $("chartBadge").textContent = `${dataset.chart.labels.length} most expensive`;
  setKpis(dataset);
  drawChart(dataset.chart);
  renderPills(dataset);
  renderTable(dataset);
}

function setKpis(d) {
  const values = ["kpiTotalRows", "kpiMarkets", "kpiTopCommodity", "kpiStatus"];
  const subs = ["kpiTotalRowsSub", "kpiMarketsSub", "kpiTopCommoditySub", "kpiStatusSub"];
  if (!d) {
    values.forEach((id) => ($(id).textContent = "—"));
    subs.forEach((id) => ($(id).textContent = ""));
    return;
  }
  const distinct = (d.stats && d.stats.distinct) || {};
  const top = d.stats && d.stats.top_by_count;

  $("kpiTotalRows").textContent = fmt(d.rows);
  $("kpiTotalRowsSub").textContent =
    d.days > 1 ? `collected over ${d.days} days` : "collected today";

  $("kpiMarkets").textContent = fmt(distinct.market);
  $("kpiMarketsSub").textContent = distinct.state ? `across ${fmt(distinct.state)} states` : "";

  $("kpiTopCommodity").textContent = top ? top.value : "—";
  $("kpiTopCommoditySub").textContent = top ? `priced at ${fmt(top.reports)} markets` : "";

  $("kpiStatus").textContent = niceDate(d.last_collected);
  $("kpiStatusSub").textContent = "date of the latest prices";
}

// Bar chart drawn as inline SVG -- no chart library, so nothing loads from a CDN.
// Horizontal bars: commodity names are long ("Arecanut(Betelnut/Supari)") and
// rotated x-axis labels collided with everything below the chart. Reading down
// a list is also plainly easier than decoding angled text.
function drawChart(chart) {
  const host = $("analyticsChart");
  const labels = chart.labels || [];
  const values = chart.values || [];
  if (!labels.length) {
    host.innerHTML = emptyState("No chart data for this dataset yet.");
    return;
  }

  const rowH = 34;
  const gap = 10;
  const padL = 210;
  const padR = 90;
  const padT = 8;
  const W = 900;
  const H = padT + labels.length * (rowH + gap);
  const plotW = W - padL - padR;
  const max = Math.max(...values) || 1;

  const rows = labels
    .map((label, i) => {
      const v = values[i];
      const w = Math.max((v / max) * plotW, 2);
      const y = padT + i * (rowH + gap);
      const short = label.length > 26 ? label.slice(0, 25) + "…" : label;
      return (
        `<g>` +
        `<text x="${padL - 12}" y="${y + rowH / 2 + 5}" class="cat" text-anchor="end">${esc(short)}` +
        `<title>${esc(label)}</title></text>` +
        `<rect x="${padL}" y="${y}" width="${w}" height="${rowH}" rx="6" class="bar"/>` +
        `<text x="${padL + w + 10}" y="${y + rowH / 2 + 5}" class="val">` +
        `₹${Math.round(v).toLocaleString("en-IN")}</text>` +
        `</g>`
      );
    })
    .join("");

  host.innerHTML =
    `<svg viewBox="0 0 ${W} ${H}" role="img" preserveAspectRatio="xMinYMin meet" ` +
    `aria-label="${esc($("chartTitle").textContent)}">${rows}</svg>`;
}

function renderPills(dataset) {
  // Pills come from the data's own top values, so they always match what is there.
  const host = $("filterPills");
  host.innerHTML = "";
  ["all"].concat(dataset.chart.labels.slice(0, 5)).forEach((v) => {
    const b = document.createElement("button");
    b.className = "pill" + (v === state.filter ? " active" : "");
    b.textContent = v === "all" ? "All" : v;
    b.onclick = () => {
      state.filter = v;
      renderPills(dataset);
      renderTable(dataset);
    };
    host.append(b);
  });
}

function renderTable(dataset) {
  const rows = dataset.preview || [];
  const columns = rows.length ? Object.keys(rows[0]) : [];
  $("tableHead").innerHTML = `<tr>${columns.map((c) => `<th>${esc(titleCase(c))}</th>`).join("")}</tr>`;

  const q = state.query.toLowerCase();
  const pill = state.filter.toLowerCase();
  const visible = rows.filter((r) => {
    const blob = Object.values(r).join(" ").toLowerCase();
    return (!q || blob.includes(q)) && (state.filter === "all" || blob.includes(pill));
  });

  $("tableBody").innerHTML = visible.length
    ? visible.map((r) => `<tr>${columns.map((c) => `<td>${esc(cell(r[c]))}</td>`).join("")}</tr>`).join("")
    : `<tr><td colspan="${columns.length || 1}" class="muted">No rows match this filter.</td></tr>`;
}

const search = $("searchInput");
if (search) {
  search.addEventListener("input", (e) => {
    state.query = e.target.value;
    if (state.active) renderTable(state.active);
  });
}

init();
