// DataPulse-India dashboard.
//
// Every figure rendered here comes from data/summary.json, which the pipeline
// generates from the collected parquet (`datapulse summarize`). Nothing on this
// page is hardcoded sample data -- if a dataset has not been collected yet, it
// says so rather than showing a placeholder number.

const SUMMARY_URL = "data/summary.json";
const $ = (id) => document.getElementById(id);

const state = { datasets: [], active: null, region: "all", query: "", sort: "places", desc: true };

const fmt = (n) => (typeof n === "number" ? n.toLocaleString("en-IN") : n ?? "—");
const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const titleCase = (c) => c.replace(/_/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
const cell = (v) =>
  v === null || v === undefined ? "—" : typeof v === "number" ? v.toLocaleString("en-IN") : v;
// "2026-08-25T12:50:09+00:00" means nothing at a glance. People read time in
// relation to now, and Indian prices in IST.
function timeAgo(iso) {
  const then = new Date(iso);
  if (isNaN(then)) return "";
  const mins = Math.round((Date.now() - then) / 60000);
  if (mins < 2) return "just now";
  if (mins < 60) return `${mins} minutes ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs} hour${hrs > 1 ? "s" : ""} ago`;
  const days = Math.round(hrs / 24);
  return days === 1 ? "yesterday" : `${days} days ago`;
}

function niceDate(value) {
  const d = new Date(value);
  if (isNaN(d)) return value || "—";
  return d.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
}

// A markup edit that renames or drops an element must not blank the page.
// Before these, a missing provenance field threw mid-render and took the KPIs,
// the chart and the table down with it.
const setText = (id, value) => {
  const el = $(id);
  if (el) el.textContent = value;
};
const setHtml = (id, value) => {
  const el = $(id);
  if (el) el.innerHTML = value;
};

const emptyState = (msg) => `<p class="muted empty-state">${esc(msg)}</p>`;

async function init() {
  let summary;
  try {
    const resp = await fetch(SUMMARY_URL, { cache: "no-store" });
    if (!resp.ok) throw new Error(String(resp.status));
    summary = await resp.json();
  } catch {
    setText("pipelineStatus", "Summary unavailable");
    setText("panelDescription",
      "data/summary.json could not be loaded. It is generated by `datapulse summarize` during the nightly run.");
    return;
  }

  state.datasets = summary.datasets || [];
  const when = summary.generated_at;
  setText("provenance",
    `Last updated ${timeAgo(when)} (${niceDate(when)}). Every number here is calculated from the ` +
    `collected data — nothing on this page is typed in by hand.`);

  const collecting = state.datasets.filter((d) => d.rows > 0).length;
  setText("pipelineStatus",
    collecting > 0 ? `Updated ${timeAgo(summary.generated_at)}` : "No data yet");

  renderTabs();
  select(state.datasets.find((d) => d.rows > 0) || state.datasets[0]);
}

function renderTabs() {
  const nav = $("domainTabs");
  nav.innerHTML = "";
  state.datasets.forEach((d) => {
    const btn = document.createElement("button");
    btn.className = "tab-btn" + (d.rows === 0 ? " is-empty" : "");
    // A dataset with no rows is labelled as such -- never dressed up as live.
    const tag =
      d.rows > 0 ? `${fmt(d.rows)} prices` : "Coming soon";
    btn.innerHTML = '<span class="tab-info"><span class="tab-title"></span><span class="tab-tag"></span></span>';
    btn.querySelector(".tab-title").textContent = d.label;
    btn.querySelector(".tab-tag").textContent = tag;
    btn.onclick = () => select(d);
    nav.append(btn);
  });
}

function select(dataset) {
  if (!dataset) return;
  state.active = dataset;
  state.region = "all";
  state.query = "";
  const searchBox = $("searchInput");
  if (searchBox) searchBox.value = "";

  const idx = state.datasets.indexOf(dataset);
  [...$("domainTabs").children].forEach((b, i) => b.classList.toggle("active", i === idx));

  setText("panelTitle", dataset.label);
  setText("chartTitle", dataset.chart_title || "");

  if (!dataset.rows) {
    setText("panelDescription",
      "We are not collecting this one yet. The pipeline is built and ready to switch on.");
    setText("chartBadge", "");
    setHtml("analyticsChart", emptyState("No data collected for this dataset yet."));
    setHtml("tableHead", "");
    setHtml("tableBody", "");
    renderRegions(dataset);
    setKpis(null);
    renderDownload(dataset);
    renderProvenance(dataset);
    return;
  }

  setText("panelDescription", dataset.preview_note);
  setText("chartBadge", `${dataset.chart.labels.length} most expensive`);
  renderDownload(dataset);
  renderProvenance(dataset);
  setKpis(dataset);
  drawChart(dataset.chart);
  renderRegions(dataset);
  renderTable(dataset);
}

// The CSV is generated at deploy time next to summary.json. If a dataset has
// none yet, hide the button rather than offering a broken download.
function renderDownload(dataset) {
  const link = $("downloadCsv");
  if (!link) return;
  if (!dataset.download) {
    link.style.display = "none";
    return;
  }
  link.style.display = "";
  link.href = `data/${dataset.download}`;
  link.textContent = `Download these ${fmt(dataset.download_rows)} prices (CSV)`;
}

function renderProvenance(dataset) {
  const p = dataset.provenance || {};
  const card = $("provenanceCard");
  if (!card) return;
  // No provenance declared means we cannot say where it came from -- so say
  // nothing rather than implying it is unsourced.
  card.style.display = Object.keys(p).length ? "" : "none";

  const link = (text, href) =>
    href ? `<a href="${esc(href)}" target="_blank" rel="noopener">${esc(text)}</a>` : esc(text);

  setHtml("provSource", p.source_name ? link(p.source_name, p.source_url) : "—");
  setText("provPublisher", p.publisher || "—");
  setHtml("provLicense", p.license ? link(p.license, p.license_url) : "—");
  setText("provCadence", p.cadence || "—");
  setText("provUnits", p.units || "—");

  const notes = $("provNotes");
  if (notes) {
    notes.innerHTML = "";
    (p.notes || []).forEach((n) => {
      const li = document.createElement("li");
      li.textContent = n;
      notes.append(li);
    });
  }
}

function setKpis(d) {
  const values = ["kpiTotalRows", "kpiMarkets", "kpiTopCommodity", "kpiStatus"];
  const subs = ["kpiTotalRowsSub", "kpiMarketsSub", "kpiTopCommoditySub", "kpiStatusSub"];
  if (!d) {
    values.forEach((id) => setText(id, "—"));
    subs.forEach((id) => setText(id, ""));
    return;
  }
  const distinct = (d.stats && d.stats.distinct) || {};
  const top = d.stats && d.stats.top_by_count;

  setText("kpiTotalRows", fmt(d.rows));
  setText("kpiTotalRowsSub", d.days > 1 ? `collected over ${d.days} days` : "collected today");

  setText("kpiMarkets", fmt(distinct.market));
  setText("kpiMarketsSub", distinct.state ? `across ${fmt(distinct.state)} states` : "");

  setText("kpiTopCommodity", top ? top.value : "—");
  setText("kpiTopCommoditySub", top ? `priced at ${fmt(top.reports)} markets` : "");

  setText("kpiStatus", niceDate(d.last_collected));
  setText("kpiStatusSub", "date of the latest prices");
}

// Bar chart drawn as inline SVG -- no chart library, so nothing loads from a CDN.
// Horizontal bars: commodity names are long ("Arecanut(Betelnut/Supari)") and
// rotated x-axis labels collided with everything below the chart. Reading down
// a list is also plainly easier than decoding angled text.
function drawChart(chart) {
  const host = $("analyticsChart");
  const labels = chart.labels || [];
  const values = chart.values || [];
  if (!labels.length) {
    host.innerHTML = emptyState("No chart data for this dataset yet.");
    return;
  }

  const rowH = 34;
  const gap = 10;
  const padL = 210;
  const padR = 90;
  const padT = 8;
  const W = 900;
  const H = padT + labels.length * (rowH + gap);
  const plotW = W - padL - padR;
  const max = Math.max(...values) || 1;

  const rows = labels
    .map((label, i) => {
      const v = values[i];
      const w = Math.max((v / max) * plotW, 2);
      const y = padT + i * (rowH + gap);
      const short = label.length > 26 ? label.slice(0, 25) + "…" : label;
      return (
        `<g>` +
        `<text x="${padL - 12}" y="${y + rowH / 2 + 5}" class="cat" text-anchor="end">${esc(short)}` +
        `<title>${esc(label)}</title></text>` +
        `<rect x="${padL}" y="${y}" width="${w}" height="${rowH}" rx="6" class="bar"/>` +
        `<text x="${padL + w + 10}" y="${y + rowH / 2 + 5}" class="val">` +
        `₹${Math.round(v).toLocaleString("en-IN")}</text>` +
        `</g>`
      );
    })
    .join("");

  host.innerHTML =
    `<svg viewBox="0 0 ${W} ${H}" role="img" preserveAspectRatio="xMinYMin meet" ` +
    `aria-label="${esc($("chartTitle").textContent)}">${rows}</svg>`;
}

// A row per crop, optionally narrowed to one state. Both views are computed by
// the pipeline -- a median of medians is not a median, so the all-India figure
// has to come from the underlying rows, not from averaging the state rows.
const COLUMNS = [
  { key: "dimension", label: "Crop", num: false },
  { key: "places", label: "Markets", num: true },
  { key: "low", label: "Cheapest", num: true, money: true },
  { key: "typical", label: "Typical", num: true, money: true },
  { key: "high", label: "Priciest", num: true, money: true },
  { key: "spread", label: "Spread", num: true, ratio: true },
];

// Under this many markets the min and max are one trader's quote, not a
// regional price -- shown, but visibly de-emphasised.
const THIN_MARKETS = 5;

function renderRegions(dataset) {
  const select = $("stateFilter");
  if (!select) return;
  const table = dataset.table || {};
  const facets = table.facets || [];
  select.innerHTML = '<option value="all">All of India</option>';
  facets.forEach((f) => {
    const o = document.createElement("option");
    o.value = f;
    o.textContent = f;
    select.append(o);
  });
  select.value = state.region;
  select.disabled = !facets.length;
}

function currentRows(dataset) {
  const table = dataset.table || {};
  if (state.region === "all") return table.overall || [];
  return (table.faceted || []).filter((r) => r[table.facet] === state.region);
}

function renderTable(dataset) {
  const table = dataset.table || {};
  const dim = table.dimension;
  if (!dim) {
    setHtml("tableHead", "");
    setHtml("tableBody", "");
    setText("tableNote", "");
    return;
  }

  setHtml("tableHead",
    "<tr>" +
    COLUMNS.map((c) => {
      const arrow = state.sort === c.key ? (state.desc ? "▼" : "▲") : "";
      return `<th class="sortable${c.num ? " num" : ""}" data-key="${c.key}">${esc(c.label)}` +
             `<span class="arrow">${arrow}</span></th>`;
    }).join("") +
    "</tr>");

  [...$("tableHead").querySelectorAll("th")].forEach((th) => {
    th.onclick = () => {
      const key = th.dataset.key;
      // Same column toggles direction; a new column starts descending, except
      // the name column which reads naturally A-Z.
      if (state.sort === key) state.desc = !state.desc;
      else { state.sort = key; state.desc = key !== "dimension"; }
      renderTable(dataset);
    };
  });

  const q = state.query.trim().toLowerCase();
  let rows = currentRows(dataset);
  if (q) rows = rows.filter((r) => String(r[dim] || "").toLowerCase().includes(q));

  const key = state.sort === "dimension" ? dim : state.sort;
  rows = [...rows].sort((a, b) => {
    const x = a[key], y = b[key];
    if (typeof x === "string" || typeof y === "string")
      return String(x || "").localeCompare(String(y || ""));
    return (x ?? -Infinity) - (y ?? -Infinity);
  });
  if (state.desc) rows.reverse();

  setHtml("tableBody", rows.length
    ? rows
        .map((r) => {
          const few = (r.places ?? 0) < THIN_MARKETS;
          return "<tr>" + COLUMNS.map((c) => {
            // Flag the market count itself rather than fading the whole row:
            // the price figures are real, only the sample behind them is thin.
            const cls = [c.num ? "num" : "", few && c.key === "places" ? "few-samples" : ""]
              .filter(Boolean).join(" ");
            const attr = cls ? ` class="${cls}"` : "";
            const title = few && c.key === "places"
              ? ' title="Few markets reporting — the cheapest and priciest are single quotes, not a regional range."'
              : "";
            const v = c.key === "dimension" ? r[dim] : r[c.key];
            if (v === null || v === undefined) return `<td${attr}>—</td>`;
            const text = c.money ? `₹${Math.round(v).toLocaleString("en-IN")}`
                       : c.ratio ? `${v}×`
                       : typeof v === "number" ? fmt(v) : v;
            return `<td${attr}${title}>${esc(text)}</td>`;
          }).join("") + "</tr>";
        })
        .join("")
    : `<tr><td colspan="${COLUMNS.length}" class="muted">No crop matches that search.</td></tr>`);

  const where = state.region === "all" ? "across India" : `in ${state.region}`;
  setText("tableNote",
    `${rows.length} crop${rows.length === 1 ? "" : "s"} ${where}. ` +
    `Prices are ₹ per quintal. A market count marked * comes from fewer than ` +
    `${THIN_MARKETS} markets — with so few reports the cheapest and priciest are single ` +
    `quotes rather than a regional range.`);
}

const regionSelect = $("stateFilter");
if (regionSelect) {
  regionSelect.addEventListener("change", (e) => {
    state.region = e.target.value;
    if (state.active) renderTable(state.active);
  });
}

const search = $("searchInput");
if (search) {
  search.addEventListener("input", (e) => {
    state.query = e.target.value;
    if (state.active) renderTable(state.active);
  });
  
  // Press / to focus search bar
  document.addEventListener("keydown", (e) => {
    if (e.key === "/" && document.activeElement !== search) {
      e.preventDefault();
      search.focus();
    }
  });
}

init();

